### PR TITLE
Feature: CMS + Orbtis as docker containers

### PR DESCRIPTION
**Pull request by jossemarGT**
First things first, this was a long shot! But finally we got a CMS + Orbits integration environment, this vagrant configuration starts 3 independent virtual machines with CMS, Orbits and the data storage services. This environment simulates at minor scale how this ecosystem should look like in the cloud.

### CODE REVIEW

**Comment by joelgtsantos** [comment]
I'm experiencing an issue when the node001 is trying to provision PostgreSQL DB and it's preventing the script init-cms-database.sh to be execute, the message is as it follows

```shell
docker-entrypoint-initdb.d $'\r': command not found
```

**Comment by joelgtsantos** [comment]
I'm experiencing an issue when the node001 is trying to provision the PostgreSQL DB and it's preventing the script init-cms-database.sh to be executed, the message is as it follows

```shell
docker-entrypoint-initdb.d $'\r': command not found
```

**Comment by joelgtsantos** [comment]
I'm experiencing an issue when the node001 is trying to provision the PostgreSQL DB and it's preventing the script init-cms-database.sh to be executed, the message is as it follows

```shell
docker-entrypoint-initdb.d $'\r': command not found on line 2
```

**Comment by jossemarGT** [comment]
Thanks for reporting that bug @joelgtsantos . Turns out that I didn't take in account the OS's where the end of line is CRLF instead of just LF, so I've enforced this through `.gitattributes`  file, git should comply with it upon checkout and the provisioning scripts should work as expected

**Pull request merged**
